language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t docker-react:v.1 -f Dockerfile.dev .

script:
    - docker run -e CI=true docker-react:v.1 npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "dockerReact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-west-2-946943555709"
    bucket_path: "dockerReact"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
